setup.cfg

chore(setup): add types-enum34 to install_requires

---

README.md

Signed-off-by: César Román <thecesrom@gmail.com>

docs: add usage instructions to README

---

.github/workflows/ci.yml

We use `mypy --py2` for running `mypy`.
`mypy` settings will come from `pyproject.toml`

ci: use settings from pyproject.toml for mypy

---

.pre-commit-config.yaml
README.md

Signed-off-by: César Román <thecesrom@gmail.com>

docs: add pre-commit.ci badge to README

---

.pre-commit-config.yaml

Forgot to add pre-commit hook on #13

build(deps): add commitizen to pre-commit

---

stubs/system/dnp3.pyi
stubs/system/gui.pyi
stubs/system/serial.pyi

Modules `dnp3`, `gui`, and `serial` do not make available their constants in `__all__`.
All constants have been added to `__all__`.
Mirroring: https://github.com/ignition-api/8.1/commit/fbdf32915255a9c269289ff77d27f134b38a2a06

feat(system): add constants to __all__

---

.github/workflows/ci.yml
requirements.txt

There is no requirements file.
Add requirements file for CI and Development.
With `mypy` v0.980 dropping Python 2 support, we must lock our dependency on `mypy` to anything less than 0.980.

ci: add requirements file for CI and Development

---

.flake8
.pre-commit-config.yaml

We are not checking our files with `flake8`.
Add `flake8` + `flake8-pyi` as a `pre-commit` hook.

build(deps): add flake8 to pre-commit

---

setup.cfg

mypy 0.980 will not support Python 2
see: <https://mypy-lang.blogspot.com/2022/07/mypy-0971-released.html>

build(pip): lock mypy dependency

---

stubs/com/inductiveautomation/ignition/common/model/__init__.pyi

Add `com.inductiveautomation.ignition.common.model.ApplicationScope`

feat(ia): add ApplicationScope class

---

setup.cfg

build(pip): create stable release

---

.github/workflows/ci.yml
tox.ini

Run `tox`, and only trigger workflow runs on `push` to `main`.

ci(github): refactor tox

---

.github/workflows/ci.yml
tox.ini

CI workflow only triggers `py3##` testenvs, thus the mypy testenv was not triggered.
The new `py310-typecheck` will be triggered.

test(tox): run type check on CI

---

.github/workflows/ci.yml

First install `tox`, then set `TOXENV` environment variable.

ci(github): reorder steps in workflow

---

pyproject.toml

build(deps): use tox.ini for isort

---

.cz.yaml
pyproject.toml
requirements.test.txt
tox.ini

create .cz.yaml and move mypy's settings to tox.ini
update deps and commands on typecheck tox env

chore(test): move cz and mypy settings

---

.github/workflows/ci.yml

Remove verbose output for `tox`.

ci: remove verbose output for tox

---

.github/workflows/ci.yml
.github/workflows/pypi_upload.yml

We are using `ubuntu-latest`
We will specifically use `ubuntu-20.04`.

ci: use ubuntu-20.04

---

.cz.yaml
.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/pypi_upload.yml
.pre-commit-config.yaml

style:
- apply style to all YAML files

ci: cache dependencies

---

.github/workflows/ci.yml
tox.ini

add requirements.txt to hashFiles used in caching tox

test(tox): add deps to py310 env

---

mypy.ini
tox.ini

format tox.ini with tox-ini-fmt

test(tox): move mypy config to its own file

---

stubs/com/inductiveautomation/ignition/common/i18n/keyboard/__init__.pyi
stubs/system/vision.pyi

feat(system): add system.vision.getKeyboardLayouts

---

.github/workflows/main.yml
.github/workflows/publish.yml

ci(github): use major version tag for workflows

---

.github/workflows/main.yml
stubs/system/bacnet/__init__.pyi

Add Ignition 8.1.32 new features

feat(system): add Ignition 8.1.32 new features

---

.cz.yaml
.github/workflows/pr-build.yml
.github/workflows/publish.yml
pyproject.toml

move commitizen config to pyproject.toml

ci: use coatl-dev/workflows@v1

---

.pre-commit-config.yaml

We use commitizen pre-commit hook.
We are removing commitizen pre-commit hook.

build(deps): remove commitizen

---

.github/workflows/pip-compile-upgrade.yml
.github/workflows/pr-build.yml
.github/workflows/publish.yml
README.md
pyproject.toml
stubs/com/inductiveautomation/ignition/common/script/__init__.pyi
tox.ini

build(pip): use Python 3.12

---

.github/workflows/pip-compile-upgrade.yml

ci(pip-compile-upgrade): update cron schedule

---

pyproject.toml
tox.ini

build(pip): drop support for Python 3.7 and 3.8
